import re
from typing import Dict, Any, List

FREE_EMAIL_PROVIDERS = {
    "gmail.com", "yahoo.com", "hotmail.com", "outlook.com", "live.com",
    "aol.com", "icloud.com", "protonmail.com", "proton.me", "mail.com", "zoho.com", "yandex.com"
}

CORPORATE_KEYWORDS = {
    "paypal", "microsoft", "google", "apple", "amazon", "netflix", "meta", "bank",
    "chase", "wells fargo", "support", "security", "billing", "helpdesk", "it-support", "admin"
}

class SenderAnalyzer:
    @classmethod
    def analyze(cls, parsed_email: Dict[str, Any]) -> List[Dict[str, Any]]:
        indicators = []
        sender = parsed_email.get("sender", "") or ""
        display_name = parsed_email.get("display_name", "") or ""
        reply_to = parsed_email.get("reply_to", "") or ""
        headers = parsed_email.get("headers", {}) or {}

        if not sender:
            indicators.append({
                "source": "sender_analysis",
                "category": "sender_identity",
                "indicator_code": "MISSING_SENDER",
                "title": "Missing Sender Address",
                "severity": "medium",
                "evidence": "No valid From address could be extracted from the email header.",
                "description": "Emails lacking a valid sender address are frequently generated by automated spam scripts or spoofing tools."
            })
            return indicators

        # Extract local part and domain
        if "@" in sender:
            local_part, domain = sender.split("@", 1)
            local_part = local_part.lower().strip()
            domain = domain.lower().strip()
        else:
            local_part = sender
            domain = ""
            indicators.append({
                "source": "sender_analysis",
                "category": "sender_identity",
                "indicator_code": "MALFORMED_SENDER_EMAIL",
                "title": "Malformed Sender Address",
                "severity": "high",
                "evidence": f"Sender address '{sender}' does not adhere to standard RFC 5322 email syntax.",
                "description": "Malformed sender addresses indicate broken spoofing scripts or intentional obfuscation."
            })

        # 1. Check Display Name Mismatch / Impersonation
        if display_name and domain:
            lower_display = display_name.lower()
            # If display name mentions a corporate brand or role, but domain is a free provider or lookalike
            for kw in CORPORATE_KEYWORDS:
                if kw in lower_display and kw not in domain:
                    indicators.append({
                        "source": "sender_analysis",
                        "category": "display_name_mismatch",
                        "indicator_code": "DISPLAY_NAME_BRAND_MISMATCH",
                        "title": "Display Name vs Sender Domain Mismatch",
                        "severity": "high",
                        "evidence": f"Display Name is '{display_name}', but sender email is '{sender}'.",
                        "description": "Attackers frequently forge the display name to mimic legitimate organizations while sending from an unrelated attacker-controlled mailbox."
                    })
                    break

        # 2. Check Free Email Provider used for Corporate / Financial Communication
        if domain in FREE_EMAIL_PROVIDERS:
            # Check if display name or local part implies official administrative authority
            if any(k in local_part or k in display_name.lower() for k in ["security", "support", "billing", "admin", "service", "verify", "paypal", "microsoft"]):
                indicators.append({
                    "source": "sender_analysis",
                    "category": "free_provider_spoof",
                    "indicator_code": "FREE_EMAIL_FOR_OFFICIAL_ROLE",
                    "title": "Free Email Provider Impersonating Official Authority",
                    "severity": "high",
                    "evidence": f"Sender '{sender}' uses a free public email provider ({domain}) while claiming official corporate or security roles.",
                    "description": "Legitimate enterprise security and billing notifications are sent from official enterprise domains, never free public webmail accounts."
                })

        # 3. Check Reply-To Mismatch
        if reply_to and domain:
            reply_domain = reply_to.split("@")[-1].lower() if "@" in reply_to else ""
            if reply_domain and reply_domain != domain:
                indicators.append({
                    "source": "sender_analysis",
                    "category": "reply_to_mismatch",
                    "indicator_code": "REPLY_TO_DOMAIN_MISMATCH",
                    "title": "Reply-To Address Diverges From Sender Domain",
                    "severity": "medium",
                    "evidence": f"From: '{sender}' vs Reply-To: '{reply_to}' (points to '{reply_domain}').",
                    "description": "A Reply-To header pointing to a different domain diverts user replies to an external attacker mailbox while keeping the From header superficially familiar."
                })

        # 4. Suspicious local part patterns
        suspicious_local_keywords = ["account-update", "security-alert", "billing-dept", "noreply-verify", "login-support"]
        if any(sk in local_part for sk in suspicious_local_keywords):
            indicators.append({
                "source": "sender_analysis",
                "category": "suspicious_local_part",
                "indicator_code": "SUSPICIOUS_SENDER_USER_PART",
                "title": "Suspicious Sender Local-Part Pattern",
                "severity": "low",
                "evidence": f"Local part '{local_part}' uses artificial urgency or security keyword combinations.",
                "description": "Automated phishing templates often generate compound administrative local parts to establish false trust."
            })

        # 5. Header Authentication Check (SPF / DKIM / DMARC)
        cls._check_auth_headers(headers, indicators)

        return indicators

    @classmethod
    def _check_auth_headers(cls, headers: Dict[str, Any], indicators: List[Dict[str, Any]]):
        if not headers:
            return

        auth_results = headers.get("Authentication-Results", "") or headers.get("authentication-results", "")
        received_spf = headers.get("Received-SPF", "") or headers.get("received-spf", "")
        dmarc_res = headers.get("DMARC-Filter", "") or ""

        combined_auth = f"{auth_results} {received_spf} {dmarc_res}".lower()

        if "spf=fail" in combined_auth or "spf=softfail" in combined_auth:
            indicators.append({
                "source": "sender_analysis",
                "category": "email_authentication",
                "indicator_code": "SPF_VALIDATION_FAILED",
                "title": "SPF Authentication Failed",
                "evidence": f"Header validation result: {received_spf or auth_results}",
                "severity": "high",
                "description": "The sending server IP is not authorized by the domain's SPF DNS record to transmit emails on its behalf."
            })
        elif "spf=pass" in combined_auth:
            # We don't necessarily raise a warning, but could record clean signal
            pass

        if "dkim=fail" in combined_auth:
            indicators.append({
                "source": "sender_analysis",
                "category": "email_authentication",
                "indicator_code": "DKIM_SIGNATURE_FAILED",
                "title": "DKIM Cryptographic Signature Invalid",
                "evidence": f"DKIM result in header: {auth_results}",
                "severity": "high",
                "description": "The email's cryptographic DKIM signature failed verification, suggesting message tampering or header forgery in transit."
            })

        if "dmarc=fail" in combined_auth:
            indicators.append({
                "source": "sender_analysis",
                "category": "email_authentication",
                "indicator_code": "DMARC_ALIGNMENT_FAILED",
                "title": "DMARC Policy Enforcement Failed",
                "evidence": f"DMARC result in header: {auth_results}",
                "severity": "high",
                "description": "The message failed the domain owner's published DMARC policy due to unaligned SPF and DKIM identifiers."
            })
